#!/usr/bin/env node
// kg-index.js — regenerate .knowledge-graph/INDEX.md, the CHEAP navigation
// surface for the meta-KG.
//
// Tokenomics (Garth 2026-07-19): graph.json is ~400KB (~100k tokens) — an
// agent that reads it whole to find one fact pays two orders of magnitude too
// much. INDEX.md is one greppable line per entity (name + hook), grouped by
// type; the intended lookup is Grep INDEX.md (costs only the matched lines)
// → `node scripts/kg-get.js <EntityName>` (costs one entity, ~1.5KB). Same
// shape as the MEMORY.md index that already works for session memory.
//
// GENERATED — never hand-edit. knowledge-graph-merkle.js regenerates it on
// every graph write; run this directly only to rebuild after a manual fix.
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { atomicWrite } = require('./lib/atomic');

const GRAPH_FILE = path.join(__dirname, '../.knowledge-graph/graph.json');
const INDEX_FILE = path.join(__dirname, '../.knowledge-graph/INDEX.md');
const HOOK_MAX = 110;

// One line per entity: the name (grep anchor) + a hook cut from the first
// observation — enough to judge relevance, never the full content. Sliced by
// code point (Array.from), not UTF-16 code unit (String.slice) — a plain
// .slice() can cut a surrogate pair in half (e.g. an emoji in an
// observation), corrupting the character and leaving an unpaired surrogate
// in INDEX.md.
function hookFor(entity) {
  const first = (entity.observations && entity.observations[0]) || '';
  const flat = String(first).replace(/\s+/g, ' ').trim();
  const chars = Array.from(flat);
  return chars.length <= HOOK_MAX ? flat : `${chars.slice(0, HOOK_MAX - 1).join('')}…`;
}

function buildIndex(graph) {
  const byType = new Map();
  for (const e of graph.entities || []) {
    const t = e.entityType || 'Untyped';
    if (!byType.has(t)) byType.set(t, []);
    byType.get(t).push(e);
  }
  const types = [...byType.keys()].sort(
    (a, b) => byType.get(b).length - byType.get(a).length || a.localeCompare(b)
  );
  const lines = [
    '# Meta-KG Index (GENERATED — do not hand-edit)',
    '',
    '<!-- Regenerated by scripts/kg-index.js on every graph write. -->',
    '<!-- Lookup: Grep this file for your topic, then -->',
    '<!--   node scripts/kg-get.js <EntityName>       -->',
    '<!-- Never read graph.json whole for a lookup.   -->',
    '',
  ];
  for (const t of types) {
    lines.push(`## ${t} (${byType.get(t).length})`);
    lines.push('');
    for (const e of byType.get(t).slice().sort((a, b) => a.name.localeCompare(b.name))) {
      lines.push(`- ${e.name} — ${hookFor(e)}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

// graphFile/indexFile default to the real repo paths so every existing call
// site (CLI, saveGraph()) is unaffected; overridable for tests so a
// regenerate() test can exercise the real read+write path against a temp
// graph without touching the real .knowledge-graph/INDEX.md.
function regenerate(graphFile = GRAPH_FILE, indexFile = INDEX_FILE) {
  const graph = JSON.parse(fs.readFileSync(graphFile, 'utf8'));
  const out = buildIndex(graph);
  atomicWrite(indexFile, out);
  return out.length;
}

module.exports = { buildIndex, hookFor, regenerate, GRAPH_FILE, INDEX_FILE };

if (require.main === module) {
  const bytes = regenerate();
  console.log(`kg-index: wrote ${INDEX_FILE} (${bytes} bytes)`);
}
